secret_key_supa = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhianVqa2V5d3JlZHBjenRtd3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjIyMDA4MDUsImV4cCI6MjAzNzc3NjgwNX0.aPH90RqfjklH3AjzSsieAT-Nkude6t0FKUQTk3i1Tsc"
supabase_url = "https://xbjujkeywredpcztmwqx.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhianVqa2V5d3JlZHBjenRtd3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjIyMDA4MDUsImV4cCI6MjAzNzc3NjgwNX0.aPH90RqfjklH3AjzSsieAT-Nkude6t0FKUQTk3i1Tsc"

# Configuração da chave API
API_KEY_gemeni = "AIzaSyBWhKAgsZoZfNx65XW7DIcYbe4L2RPESQI"

HANGFACE_TOKEN = "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"